name: Build

env:
  DEST_DIR: wheelhouse
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: python -m pip install --upgrade setuptools wheel

      - name: Build wheels
        run: python3 setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: wheel-dist
          path: dist